name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker Build and Push
    steps:    

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/filelist-api-whitelist:latest